import { projectAssetUrl } from '../lib/project-assets';

export type AudioChannel = 'interface' | 'card' | 'magic' | 'destructive';

export type AudioCueDefinition = {
  sources: readonly string[];
  channel: AudioChannel;
  gain: number;
  cooldownMs: number;
  maxVoices: number;
  playbackRate: readonly [number, number];
  maxDuration?: number;
  latencyBudgetMs: number;
  preload?: boolean;
  ducking?: number;
};

const cardAudio = projectAssetUrl('userscript-deck/audio/card');
const effectsAudio = projectAssetUrl('userscript-deck/audio/effects');

export const FORGE_AUDIO_DURATION = 2.64;

export const AUDIO_CUES = {
  uiHover: {
    sources: [`${cardAudio}/slide-02.mp3`],
    channel: 'interface',
    gain: 0.13,
    cooldownMs: 80,
    maxVoices: 2,
    playbackRate: [1.03, 1.08],
    maxDuration: 0.28,
    latencyBudgetMs: 100,
    preload: true,
  },
  uiPress: {
    sources: [`${cardAudio}/coin-flip-03.mp3`],
    channel: 'interface',
    gain: 0.19,
    cooldownMs: 55,
    maxVoices: 2,
    playbackRate: [1.04, 1.08],
    maxDuration: 0.36,
    latencyBudgetMs: 120,
    preload: true,
  },
  uiConfirm: {
    sources: [`${cardAudio}/reveal-10.mp3`],
    channel: 'interface',
    gain: 0.2,
    cooldownMs: 90,
    maxVoices: 2,
    playbackRate: [1.02, 1.06],
    maxDuration: 0.52,
    latencyBudgetMs: 160,
    preload: true,
  },
  deckHover: {
    sources: [`${cardAudio}/shuffle-02.mp3`],
    channel: 'card',
    gain: 0.15,
    cooldownMs: 180,
    maxVoices: 1,
    playbackRate: [1.04, 1.07],
    maxDuration: 0.34,
    latencyBudgetMs: 120,
  },
  deckOpen: {
    sources: [`${cardAudio}/shuffle-02.mp3`],
    channel: 'card',
    gain: 0.42,
    cooldownMs: 320,
    maxVoices: 1,
    playbackRate: [0.98, 1.01],
    maxDuration: 1.08,
    latencyBudgetMs: 500,
  },
  deckClose: {
    sources: [`${cardAudio}/shuffle-01.mp3`],
    channel: 'card',
    gain: 0.36,
    cooldownMs: 320,
    maxVoices: 1,
    playbackRate: [1.02, 1.05],
    maxDuration: 1.12,
    latencyBudgetMs: 500,
  },
  cardDeal: {
    sources: [
      `${cardAudio}/deal-04.mp3`,
      `${cardAudio}/deal-03.mp3`,
      `${cardAudio}/deal-05.mp3`,
    ],
    channel: 'card',
    gain: 0.23,
    cooldownMs: 65,
    maxVoices: 4,
    playbackRate: [0.98, 1.04],
    maxDuration: 0.72,
    latencyBudgetMs: 240,
  },
  cardCollect: {
    sources: [`${cardAudio}/place-08.mp3`, `${cardAudio}/place-05.mp3`],
    channel: 'card',
    gain: 0.18,
    cooldownMs: 58,
    maxVoices: 3,
    playbackRate: [1.03, 1.09],
    maxDuration: 0.45,
    latencyBudgetMs: 180,
  },
  cardHover: {
    sources: [`${cardAudio}/slide-02.mp3`, `${cardAudio}/slide-01.mp3`],
    channel: 'card',
    gain: 0.17,
    cooldownMs: 72,
    maxVoices: 2,
    playbackRate: [1.01, 1.07],
    maxDuration: 0.32,
    latencyBudgetMs: 100,
  },
  cardPress: {
    sources: [`${cardAudio}/draw-01.mp3`],
    channel: 'card',
    gain: 0.28,
    cooldownMs: 90,
    maxVoices: 2,
    playbackRate: [1, 1.04],
    maxDuration: 0.52,
    latencyBudgetMs: 130,
  },
  cardLift: {
    sources: [`${cardAudio}/draw-05.mp3`],
    channel: 'card',
    gain: 0.34,
    cooldownMs: 120,
    maxVoices: 1,
    playbackRate: [0.98, 1.02],
    maxDuration: 0.74,
    latencyBudgetMs: 180,
  },
  cardReorder: {
    sources: [`${cardAudio}/slide-02.mp3`, `${cardAudio}/slide-03.mp3`],
    channel: 'card',
    gain: 0.15,
    cooldownMs: 95,
    maxVoices: 2,
    playbackRate: [1.04, 1.11],
    maxDuration: 0.3,
    latencyBudgetMs: 100,
  },
  cardPlace: {
    sources: [`${cardAudio}/place-08.mp3`, `${cardAudio}/place-05.mp3`],
    channel: 'card',
    gain: 0.35,
    cooldownMs: 110,
    maxVoices: 2,
    playbackRate: [0.99, 1.04],
    maxDuration: 0.82,
    latencyBudgetMs: 220,
  },
  cardReturn: {
    sources: [`${cardAudio}/place-07.mp3`],
    channel: 'card',
    gain: 0.27,
    cooldownMs: 120,
    maxVoices: 1,
    playbackRate: [1.03, 1.07],
    maxDuration: 0.62,
    latencyBudgetMs: 180,
  },
  cardFlip: {
    sources: [`${cardAudio}/flip-01.mp3`, `${cardAudio}/flip-02.mp3`],
    channel: 'card',
    gain: 0.32,
    cooldownMs: 100,
    maxVoices: 2,
    playbackRate: [0.99, 1.04],
    maxDuration: 0.78,
    latencyBudgetMs: 220,
  },
  actionOpen: {
    sources: [`${cardAudio}/reveal-10.mp3`],
    channel: 'magic',
    gain: 0.39,
    cooldownMs: 180,
    maxVoices: 1,
    playbackRate: [0.98, 1.01],
    maxDuration: 1.04,
    latencyBudgetMs: 260,
  },
  actionAttach: {
    sources: [`${effectsAudio}/action-attach.mp3`],
    channel: 'magic',
    gain: 0.42,
    cooldownMs: 105,
    maxVoices: 2,
    playbackRate: [1, 1.05],
    maxDuration: 0.6,
    latencyBudgetMs: 240,
  },
  actionDetach: {
    sources: [`${cardAudio}/slide-02.mp3`],
    channel: 'magic',
    gain: 0.18,
    cooldownMs: 90,
    maxVoices: 1,
    playbackRate: [0.88, 0.92],
    maxDuration: 0.3,
    latencyBudgetMs: 110,
  },
  actionCancel: {
    sources: [`${cardAudio}/turn-pass-04.mp3`],
    channel: 'card',
    gain: 0.29,
    cooldownMs: 150,
    maxVoices: 1,
    playbackRate: [1.03, 1.06],
    maxDuration: 0.72,
    latencyBudgetMs: 220,
  },
  panelOpen: {
    sources: [`${cardAudio}/reveal-09.mp3`],
    channel: 'interface',
    gain: 0.3,
    cooldownMs: 180,
    maxVoices: 1,
    playbackRate: [0.99, 1.02],
    maxDuration: 0.88,
    latencyBudgetMs: 260,
  },
  panelClose: {
    sources: [`${cardAudio}/turn-pass-02.mp3`],
    channel: 'interface',
    gain: 0.24,
    cooldownMs: 180,
    maxVoices: 1,
    playbackRate: [1.04, 1.08],
    maxDuration: 0.62,
    latencyBudgetMs: 200,
  },
  cast: {
    sources: [`${effectsAudio}/cast.mp3`],
    channel: 'magic',
    gain: 0.56,
    cooldownMs: 140,
    maxVoices: 2,
    playbackRate: [0.98, 1.03],
    maxDuration: 0.47,
    latencyBudgetMs: 320,
    ducking: 0.78,
  },
  contentBlockEnergyImpact: {
    sources: [`${effectsAudio}/content-blocking-energy.mp3`],
    channel: 'destructive',
    gain: 0.52,
    cooldownMs: 90,
    maxVoices: 2,
    playbackRate: [0.98, 1.03],
    maxDuration: 1.15,
    latencyBudgetMs: 260,
    ducking: 0.78,
  },
  contentBlockSwordImpact: {
    sources: [`${effectsAudio}/content-blocking-sword.mp3`],
    channel: 'destructive',
    gain: 0.5,
    cooldownMs: 90,
    maxVoices: 2,
    playbackRate: [0.98, 1.02],
    maxDuration: 1.35,
    latencyBudgetMs: 260,
    ducking: 0.76,
  },
  castCharge: {
    sources: [`${effectsAudio}/cast-charge.mp3`],
    channel: 'magic',
    gain: 0.48,
    cooldownMs: 420,
    maxVoices: 1,
    playbackRate: [2.12, 2.16],
    maxDuration: 1.68,
    latencyBudgetMs: 420,
    ducking: 0.62,
  },
  toggle: {
    sources: [`${effectsAudio}/toggle.mp3`],
    channel: 'magic',
    gain: 0.48,
    cooldownMs: 160,
    maxVoices: 1,
    playbackRate: [0.98, 1.02],
    maxDuration: 0.72,
    latencyBudgetMs: 340,
    ducking: 0.84,
  },
  update: {
    sources: [`${effectsAudio}/update.mp3`],
    channel: 'magic',
    gain: 0.48,
    cooldownMs: 260,
    maxVoices: 1,
    playbackRate: [1, 1.02],
    maxDuration: 1.8,
    latencyBudgetMs: 600,
    ducking: 0.72,
  },
  cardRemove: {
    sources: [`${cardAudio}/discard-04.mp3`],
    channel: 'destructive',
    gain: 0.48,
    cooldownMs: 240,
    maxVoices: 1,
    playbackRate: [0.96, 0.99],
    maxDuration: 1.25,
    latencyBudgetMs: 340,
    ducking: 0.66,
  },
  cardBurn: {
    sources: [`${effectsAudio}/burn.mp3`],
    channel: 'destructive',
    gain: 0.46,
    cooldownMs: 400,
    maxVoices: 1,
    playbackRate: [1.02, 1.04],
    maxDuration: 2.1,
    latencyBudgetMs: 900,
    ducking: 0.58,
  },
  forgeStart: {
    sources: [`${effectsAudio}/update.mp3`],
    channel: 'magic',
    gain: 0.52,
    cooldownMs: 500,
    maxVoices: 1,
    playbackRate: [0.99, 1.01],
    maxDuration: FORGE_AUDIO_DURATION,
    latencyBudgetMs: 900,
    ducking: 0.58,
  },
  forgeComplete: {
    sources: [`${cardAudio}/reveal-11.mp3`],
    channel: 'magic',
    gain: 0.5,
    cooldownMs: 350,
    maxVoices: 1,
    playbackRate: [0.98, 1.01],
    maxDuration: 1.7,
    latencyBudgetMs: 500,
    ducking: 0.72,
  },
  gameSuccess: {
    sources: [`${cardAudio}/reveal-11.mp3`],
    channel: 'magic',
    gain: 0.44,
    cooldownMs: 280,
    maxVoices: 1,
    playbackRate: [1.03, 1.06],
    maxDuration: 1.35,
    latencyBudgetMs: 420,
    ducking: 0.78,
  },
  gameFailure: {
    sources: [`${cardAudio}/discard-06.mp3`],
    channel: 'destructive',
    gain: 0.34,
    cooldownMs: 280,
    maxVoices: 1,
    playbackRate: [0.92, 0.96],
    maxDuration: 1.1,
    latencyBudgetMs: 360,
    ducking: 0.82,
  },
} as const satisfies Record<string, AudioCueDefinition>;

export type AudioCue = keyof typeof AUDIO_CUES;

export const PRELOAD_CUES = Object.entries(AUDIO_CUES)
  .filter(([, definition]) => 'preload' in definition && definition.preload)
  .map(([cue]) => cue as AudioCue);
